# Development dependencies only - Node.js apps run natively
services:
  # Database with development data
  postgres:
    image: postgres:15-alpine
    container_name: ridehive-postgres-dev
    environment:
      POSTGRES_DB: ridehive_dev
      POSTGRES_USER: ridehive
      POSTGRES_PASSWORD: ridehive123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./server/db/dev-data.sql:/docker-entrypoint-initdb.d/02-dev-data.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ridehive -d ridehive_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: ridehive-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local