name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history for proper deployment
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lints
      run: npm run lint
    
    - name: Run tests
      run: npm run test
      continue-on-error: true # Continue even if tests fail (since tests are minimal)
    
    - name: Build web client
      run: npm run build
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        buildpack: heroku/nodejs
        procfile: "web: NODE_ENV=production node server/server.js"
        
    - name: Run database migrations (if any)
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
        dontuseforce: true
        command: "heroku run 'cd server && node -e \"const { query } = require('./db/database'); const fs = require('fs'); if (fs.existsSync('./db/migrations/001_add_dual_pins.sql')) { const sql = fs.readFileSync('./db/migrations/001_add_dual_pins.sql', 'utf8'); query(sql).then(() => console.log('Migration complete')).catch(console.error); }\"' --app ${{ secrets.HEROKU_APP_NAME }}"
      continue-on-error: true # Don't fail if migration already ran
        
    - name: Health check
      run: |
        sleep 30 # Wait for deployment to complete
        curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health || exit 1
      continue-on-error: true

    - name: Deployment notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful! App available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
        else
          echo "❌ Deployment failed!"
        fi